### ISSUE TITLE
 Exception during node startup

### ISSUE THREAD

**Issue by shikhadabas** [corda/corda-settler#17]
I am trying to run runnodes command inside nodes folder after successful execution of deployNodes command. Four Nodes are getting invoked- Notary, PartyA, partyB, Oracle. Notary nodes is in working state but in PartyA, PartyB, Oracle nodes I am getting below mentioned error:-
[ERROR] 15:19:15+0530 [main] internal.NodeStartupLogging.invoke - Exception during node startup: Attempting to register over an existing platform flow: class net.corda.confidential.SwapIdentitiesFlow [errorCode=aixp30, moreInformationAt=https://errors.corda.net/OS/5.0-SNAPSHOT/aixp30]

I am working on Windows.
Please look into the issue and help. Thanks

**Comment by roger3cev** [comment]
I'll have a look @shikhadabas - thanks

**Comment by yikailim93** [comment]
Hi shikhadabas, just wondering if you have solved this issue because I'm encountering the same.. I was able to deployNodes at first but after recloning the project and deploying it again the problem appears

**Comment by yikailim93** [comment]
> I am trying to run runnodes command inside nodes folder after successful execution of deployNodes command. Four Nodes are getting invoked- Notary, PartyA, partyB, Oracle. Notary nodes is in working state but in PartyA, PartyB, Oracle nodes I am getting below mentioned error:-
> [ERROR] 15:19:15+0530 [main] internal.NodeStartupLogging.invoke - Exception during node startup: Attempting to register over an existing platform flow: class net.corda.confidential.SwapIdentitiesFlow [errorCode=aixp30, moreInformationAt=https://errors.corda.net/OS/5.0-SNAPSHOT/aixp30]
> 
> I am working on Windows.
> Please look into the issue and help. Thanks

Hi shikhadabas, just wondering if you have solved this issue because I'm encountering the same.. I was able to deployNodes at first but after recloning the project and deploying it again the problem appears

**Comment by VladislavIvanov** [comment]
> > I am trying to run runnodes command inside nodes folder after successful execution of deployNodes command. Four Nodes are getting invoked- Notary, PartyA, partyB, Oracle. Notary nodes is in working state but in PartyA, PartyB, Oracle nodes I am getting below mentioned error:-
> > [ERROR] 15:19:15+0530 [main] internal.NodeStartupLogging.invoke - Exception during node startup: Attempting to register over an existing platform flow: class net.corda.confidential.SwapIdentitiesFlow [errorCode=aixp30, moreInformationAt=https://errors.corda.net/OS/5.0-SNAPSHOT/aixp30]
> > I am working on Windows.
> > Please look into the issue and help. Thanks
> 
> Hi shikhadabas, just wondering if you have solved this issue because I'm encountering the same.. I was able to deployNodes at first but after recloning the project and deploying it again the problem appears

I have the same problem. Мy last working demo is with the commit of March 20th.

**Comment by roger3cev** [comment]
Try using the latest mater - it should work fine now. Cheers
